### ISSUE TITLE
Cannot activate the virtual environment

### ISSUE THREAD

**Issue by thorungb** [VorakornLeechavanan/ku-polls#33]
I cannot activate the virtual environment following the your [How to run?](https://github.com/VorakornLeechavanan/ku-polls/blob/main/README.md#how-to-run) in **README.md** <br>
Activate a virtual environment. To stop activating, write "deactivate" in the terminal.

```
. env/bin/activate
```

**Comment by VorakornLeechavanan** [comment]
Already changed the command for activating, hope it works successfully. Thank you!
