### ISSUE TITLE
Suggestion: You should include all iteration tasks board and suggest about your sub-dir

### ISSUE THREAD

**Issue by thorungb** [VorakornLeechavanan/ku-polls#36]
This is my suggestion,
- You should include ALL @VorakornLeechavanan's iterations tasks board into one 'ku-polls' task board and create sub-broads for each iteration separately.
- Your subdirectory looks different from other people's e.g. You don't have polls/static/polls/style.css (from Django tutorial part 6) in your directory. Don't worry about it because your application is still working but it might be easier if you want to beautify your application more by using CSS.

**Comment by VorakornLeechavanan** [comment]
Thank you very much for the suggestions
